main(List<String> args) {
  // LES MAP

  //DECLARER UNE MAP OU INSTANCIER

  //AJOUTER DES ELEMENTS DANS UNE MAP

  //SURPPRIMER DES ELEMENTS DANS UNE MAP

  //AJOUTER PLUSIEURS ELEMENTS DANS UNE MAP
}
